server:
  port: 7034
  servlet:
    session:
      cookie:
        name: SSOCLIENT2TXORDER
#服务的名称
spring:
  application:
    name: security-tx-order



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7031/eureka