org: #配置hmily的数据库
  dromara:
    hmily :
      serializer : kryo
      recoverDelayTime : 30
      retryMax : 30
      scheduledDelay : 30
      scheduledThreadMax :  10
      repositorySupport : db
      started: true #事务发起方，如果是事务发起方需要这里填写true
      hmilyDbConfig :
        driverClassName  : com.mysql.jdbc.Driver
        url :  jdbc:mysql://localhost:5023/hmily?useUnicode=true
        username : root
        password : 123456