server:
  port: 7029
  servlet:
   session:
     cookie:
       name: SSOCLIENT2SESSIONPRICE  
#服务的名称
spring:
  application:
    name: security-api-price
  
 
security:
  oauth2:
    client:
      client-id: priceServer
      client-secret:  123456     
    resource:
      jwt:
        key-uri: http://auth.security.com:7024/oauth/token_key  