global:
  scrape_interval: 15s #拉取数据频率

scrape_configs:
- job_name: 'springboot-app'
  scrape_interval: 10s
  metrics_path: '/actuator/prometheus' #拉取数据的接口
  
  static_configs:
  - targets: ['172.20.10.5:7025'] #指定目标的数据地址
    labels:
      application: 'springboot-app'
      
- job_name: 'prometheus'
  scrape_interval: 5s

  
  static_configs:
  - targets: ['localhost:9090']

    
