server:
  port: 7036
  servlet:
    session:
      cookie:
        name: SESSIONHEIMATXEURAKA
#服务的名称
spring:
  application:
    name: security-heima-tx-euraka



eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7036/eureka #这里连接自己