server:
  port: 7027
  servlet:
   session:
     cookie:
       name: SSOCLIENT2SESSIONAMIDN
#服务的名称
spring:
  application:
    name: security-api-admin
    
zuul:
  routes:
    #做处理，然后建立一个filter 就可以拦截这个请求
    api:
      url: http://security.geteway.com:7026
  sensitive-headers:
 
