server:
  port: 7033
  servlet:
    session:
      cookie:
        name: SSOCLIENT2TXUSER
#服务的名称
spring:
  application:
    name: spring-tx-user



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7031/eureka
      
