server:
  port: 7026
  servlet:
   session:
     cookie:
       name: SSOCLIENT2SESSIONZUUL 
#服务的名称
spring:
  application:
    name: security-api-getway
  
zuul:
  routes:
  #只做返回前端请求用户信息 url 这个地址随便写 主要是为了拦截 /user/me 这个请求
    user:
      url: http://localhost:7025
    #资源服务器
    order:
      url: http://localhost:7025
    #认证服务器
    token:
      url: http://auth.security.com:7024
      ##需要忽略的header 如果为空那么不忽略，都进行转发
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: jpa
    default-policy-list: #默认配置 如果没有具体配置明细
    - limit: 2 #限制次数
      quota: 1 #最大时间为1秒
      refresh-interval: 3 #3秒内
      # 以上语句的意思： 3秒内只允许通过2次请求 ，2次的请求的时间不能超过1秒 否则限流
      type:
      - url
      - httpmethod
      #- user # 这个一般不用 需要secrity的支持
      #- origin #ip 客户端id
    policy-list: #配置了 就会配置
       token:
        - limit: 2 #限制次数
          quota: 1 #最大时间为1秒
          refresh-interval: 3 #3秒内
          # 以上语句的意思： 3秒内只允许通过2次请求 ，2次的请求的时间不能超过1秒 否则限流
          type:
          - url
          - httpmethod
          
security:
  oauth2:
    client:
      client-id: geteway
      client-secret:  123456     
    resource:
      jwt:
        key-uri: http://auth.security.com:7024/oauth/token_key  
        
           
     
      
    


