version: "3"
services:
  prometheus:
    image: prom/prometheus:v2.4.3
    container_name: 'prometheus' #实例名称
    volumes: #挂靠 找配置 将本地的这个文替换到容器的/etc/prometheus/
    - ./prometheus/:/etc/prometheus/
    ports:
    - '9092:9090' #‘docker外的端口：docker里面的端口’
  grafana:
    image: grafana/grafana:5.2.4
    container_name: 'grafana'
    volumes:
    - ./grafana/:/etc/grafana/
    ports:
    - '3000:3000'
    volumes:
    - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini #将我们本地目录路的这个grafana.ini 替换我们容器的grafana.ini 这个文件
    - ./grafana/provisioning/:/etc/grafana/provisioning/ #吧我们本地的这个目录替换我们容器的这个目录
    env_file:
    - ./grafana/config.monitoring #环境配置文件
    depends_on: #依赖promethus 
    - prometheus
    