server:
  port: 7025
  servlet:
   session:
     cookie:
       name: SSOCLIENT2SESSIONODER 
#服务的名称
spring:
  application:
    name: security-api-order
  
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.security.com:7024/oauth/token_key
    client:
      client-id: orderServer
      client-secret:  123456       
