server:
  port: 7025
  servlet:
   session:
     cookie:
       name: SSOCLIENT2SESSIONODER 
#服务的名称
spring:
  application:
    name: security-api-order
  cloud:
    sentinel:
      transport:
        port:  7028 #这个sentinel 会在这个端口启动一个心跳项目
        dashboard: http://localhost:7030 #注册地址
  
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.security.com:7024/oauth/token_key
    client:
      client-id: orderServer
      client-secret:  123456     

sentinel:
  zookeeper:
    address: zookeeper.com:2181
    path: /sentinel_rule_config
    
    
#暴露端点 只能是这些
management:
  endpoints:
    prometheus: # 只有这样子下面的暴露的才会起作用
      enable: true
    web:
      exposure:
        include:
        - prometheus
        - info
        - health
    
        
